


export const Action_MOVIE_Types={
    DATA_LOAD:"DATA_LOAD",
    DATA_SUCCESS:"DATA_SUCCESS",
    DATA_ERROR:"DATA_ERROR",
    DATA_ADD_LIST:"DATA_ADD_LIST",
    REMOVE_FROM_LIST:"REMOVE_FROM_LIST"
}


